<?php

namespace Database\Seeders;

use App\Repositories\JobOfferRepository;
use Illuminate\Database\Seeder;

class JobOfferSeeder extends Seeder
{
    public function run(): void
    {
        $offers = [
            [
                'title' => 'Commercial(e) Junior / Stagiaire en Action Commerciale',
                'company' => 'TestPro',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Participer à la prospection et à la promotion des formations de TestPro auprès des entreprises locales.',
                'is_active' => true,
            ],
            [
                'title' => 'Testeur en Automatisation (H/F)',
                'company' => 'TestPro',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Concevoir et maintenir des scripts de tests automatisés pour nos solutions logicielles.',
                'is_active' => true,
            ],
            [
                'title' => 'Analyste QA Junior',
                'company' => 'InnovApps',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Réaliser des plans de test et assurer la validation fonctionnelle des nouvelles applications internes.',
                'is_active' => true,
            ],
            [
                'title' => 'Développeur Web PHP',
                'company' => 'SoftTech',
                'location' => 'Yamoussoukro, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Concevoir des fonctionnalités web en PHP et garantir leur qualité à travers des tests unitaires.',
                'is_active' => true,
            ],
            [
                'title' => 'Scrum Master',
                'company' => 'AgilSoft',
                'location' => 'Dakar, Sénégal',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Accompagner les équipes de développement dans l'adoption des pratiques agiles et faciliter les cérémonies Scrum.",
                'is_active' => true,
            ],
            [
                'title' => 'Consultant(e) Test Logiciel',
                'company' => 'QualiTest',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Mettre en place des stratégies de tests pour nos clients du secteur bancaire.',
                'is_active' => true,
            ],
            [
                'title' => 'Chef de Projet Digital',
                'company' => 'MediaPlus',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Piloter des projets web et coordonner les équipes techniques et marketing.',
                'is_active' => true,
            ],
            [
                'title' => 'Administrateur Systèmes Linux',
                'company' => 'DataCenter CI',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Assurer la gestion quotidienne des serveurs Linux et veiller à leur disponibilité.',
                'is_active' => true,
            ],
            [
                'title' => 'UX/UI Designer',
                'company' => 'CreativLab',
                'location' => 'Bouaké, Côte d\'Ivoire',
                'type' => 'Contract',
                'salary' => null,
                'description' => "Concevoir des interfaces utilisateurs intuitives et optimiser l'expérience client sur nos produits digitaux.",
                'is_active' => true,
            ],
            [
                'title' => 'Ingénieur DevOps',
                'company' => 'CloudBridge',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Automatiser les déploiements applicatifs et maintenir l'infrastructure cloud.",
                'is_active' => true,
            ],
            [
                'title' => 'Support Technique Niveau 1',
                'company' => 'TechCare',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Prendre en charge les demandes clients et assurer la résolution rapide des incidents techniques.',
                'is_active' => true,
            ],
            [
                'title' => 'Développeur Front-End React',
                'company' => 'DigitalWorks',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Développer des interfaces utilisateurs dynamiques avec React et intégrer les API REST.',
                'is_active' => true,
            ],
            [
                'title' => 'Administrateur Base de Données',
                'company' => 'DataSecure',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Gérer l'administration des bases de données et optimiser les performances SQL.",
                'is_active' => true,
            ],
            [
                'title' => 'Rédacteur Technique',
                'company' => 'DocuPro',
                'location' => 'Dakar, Sénégal',
                'type' => 'Contract',
                'salary' => null,
                'description' => 'Produire la documentation utilisateur et les manuels de formation de nos produits logiciels.',
                'is_active' => true,
            ],
            [
                'title' => 'Responsable Marketing Digital',
                'company' => 'MarketLive',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Élaborer la stratégie de communication en ligne et piloter les campagnes publicitaires.',
                'is_active' => true,
            ],
            [
                'title' => 'Gestionnaire de Projet IT',
                'company' => 'InfoSys',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Assurer le suivi des projets informatiques et coordonner les équipes techniques.',
                'is_active' => true,
            ],
            [
                'title' => 'Stagiaire Développement Mobile',
                'company' => 'AppFactory',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Internship',
                'salary' => null,
                'description' => "Participer au développement d'applications mobiles Android et iOS sous la supervision de l'équipe senior.",
                'is_active' => true,
            ],
            [
                'title' => 'Technicien Réseau',
                'company' => 'NetSolutions',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Installer et maintenir les équipements réseau pour nos clients professionnels.',
                'is_active' => true,
            ],
            [
                'title' => 'Ingénieur Sécurité Informatique',
                'company' => 'SecureIT',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Mettre en place des politiques de sécurité et surveiller les vulnérabilités des systèmes.',
                'is_active' => true,
            ],
            [
                'title' => 'Community Manager',
                'company' => 'ComAgency',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Contract',
                'salary' => null,
                'description' => 'Animer les réseaux sociaux et gérer les interactions avec notre communauté en ligne.',
                'is_active' => true,
            ],
            [
                'title' => 'Chef de Produit Logiciel',
                'company' => 'SoftManage',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Définir la feuille de route produit et coordonner les développements avec les équipes techniques.',
                'is_active' => true,
            ],
            [
                'title' => 'Analyste Données',
                'company' => 'DataInsight',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Collecter et analyser les données afin de produire des rapports d'aide à la décision.",
                'is_active' => true,
            ],
            [
                'title' => 'Formateur Logiciel',
                'company' => 'EduTech',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Animer des sessions de formation pour nos utilisateurs sur divers outils numériques.',
                'is_active' => true,
            ],
            [
                'title' => 'Développeur .NET',
                'company' => 'DevCorp',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Développer et maintenir des applications d.NET dans un environnement agile.",
                'is_active' => true,
            ],
            [
                'title' => 'Gestionnaire de Contenu Web',
                'company' => 'WebMedia',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Contract',
                'salary' => null,
                'description' => 'Créer et mettre à jour le contenu éditorial de nos sites internet.',
                'is_active' => true,
            ],
            [
                'title' => 'Coordinateur(trice) Formation',
                'company' => 'LearnPlus',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Organiser les plannings de formation et suivre la satisfaction des participants.',
                'is_active' => true,
            ],
            [
                'title' => 'Architecte Logiciel',
                'company' => 'ArchTech',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Concevoir l'architecture des nouvelles solutions logicielles et assurer leur évolutivité.",
                'is_active' => true,
            ],
            [
                'title' => 'Responsable Support Client',
                'company' => 'ServLine',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Superviser l'équipe de support et garantir la qualité du service rendu aux utilisateurs.",
                'is_active' => true,
            ],
            [
                'title' => 'Stagiaire QA',
                'company' => 'TestLab',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Internship',
                'salary' => null,
                'description' => "Participer à la rédaction des cas de test et à l'exécution des campagnes de validation.",
                'is_active' => true,
            ],
            [
                'title' => 'Chef de Projet Technique',
                'company' => 'ITProject',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => 'Coordonner la réalisation technique des projets et assurer le respect des délais.',
                'is_active' => true,
            ],
            [
                'title' => 'Développeur Python',
                'company' => 'DataApps',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Full Time',
                'salary' => null,
                'description' => "Créer des applications Python robustes et participer à l'implémentation de services web.",
                'is_active' => true,
            ],
            [
                'title' => 'Testeur Fonctionnel',
                'company' => 'QualiSoft',
                'location' => 'Abidjan, Côte d\'Ivoire',
                'type' => 'Contract',
                'salary' => null,
                'description' => 'Exécuter les scénarios de test fonctionnel et consigner les anomalies détectées.',
                'is_active' => true,
            ],
        ];

        foreach ($offers as $offer) {
            JobOfferRepository::create($offer);
        }
    }
}
