services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: php-app
    restart: unless-stopped
    init: true
    # Expose PHP-FPM port (for use with a web server like nginx)
    ports:
      - "9000:9000"
    # env_file: ./.env  # Uncomment if .env file exists
    networks:
      - appnet
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: jerry_clexcellence
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: jerry_clexcellence
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - appnet

# Network for inter-service communication
networks:
  appnet:
    driver: bridge

volumes:
  dbdata:
