version: "3.8"

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: php-app
    restart: unless-stopped
    init: true
    ports:
      - "9000:9000"
    # env_file: ./.env
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
