version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_ecole_pro_app
    ports:
      - "8053:80"
    depends_on:
      - db
    env_file: .env

  db:
    image: mysql:8.0
    container_name: tes_ecole_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: jerry_clexcellence
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
