version: '3.8'

services:
  testpro_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testpro_app
    ports:
      - "8000:80"
    depends_on:
      - testpro_db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: testpro_db
      DB_PORT: 3306
      DB_DATABASE: testpro
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./public:/var/www/html/public:cached
      - ./src:/var/www/html
    networks:
      - testpro_network

  testpro_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: testpro_phpmyadmin
    restart: always
    depends_on:
      - testpro_db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: testpro_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - testpro_network

  testpro_db:
    image: mysql:8.0
    restart: always
    container_name: testpro_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testpro
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  testpro_network:
    driver: bridge